"""remove_department_degree_level_semester_fields

Revision ID: 5504d2dda6c4
Revises: 7d9c4f2e8b1a
Create Date: 2026-06-27 21:53:46.215476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5504d2dda6c4'
down_revision: Union[str, Sequence[str], None] = '7d9c4f2e8b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('instructors_department_id_fkey'), 'instructors', type_='foreignkey')
    op.drop_column('instructors', 'degree_level')
    op.drop_column('instructors', 'department_id')
    op.drop_constraint(op.f('students_department_id_fkey'), 'students', type_='foreignkey')
    op.drop_constraint(op.f('fk_students_program_id'), 'students', type_='foreignkey')
    op.drop_column('students', 'batch_year')
    op.drop_column('students', 'current_semester')
    op.drop_column('students', 'program_id')
    op.drop_column('students', 'degree_level')
    op.drop_column('students', 'department_id')
    op.drop_column('students', 'enrolled_semester')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('enrolled_semester', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('degree_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('program_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('current_semester', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('batch_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_students_program_id'), 'students', 'programs', ['program_id'], ['id'])
    op.create_foreign_key(op.f('students_department_id_fkey'), 'students', 'departments', ['department_id'], ['id'])
    op.add_column('instructors', sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('instructors', sa.Column('degree_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('instructors_department_id_fkey'), 'instructors', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###
