"""add_profile_fields_to_student_and_instructor

Revision ID: a3b5aefb1bd9
Revises: cc61878cef36
Create Date: 2026-06-27 00:13:47.833542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b5aefb1bd9'
down_revision: Union[str, Sequence[str], None] = 'cc61878cef36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('instructors', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('instructors', sa.Column('address', sa.String(), nullable=True))
    op.add_column('students', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('students', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('students', sa.Column('enrolled_semester', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('address', sa.String(), nullable=True))
    op.alter_column('students', 'current_semester',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'current_semester',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('students', 'address')
    op.drop_column('students', 'enrolled_semester')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    op.drop_column('instructors', 'address')
    op.drop_column('instructors', 'last_name')
    op.drop_column('instructors', 'first_name')
    # ### end Alembic commands ###
